"""watchlist

Revision ID: 69f2c4f81334
Revises: 1e807f2c8231
Create Date: 2021-01-09 19:31:29.283814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f2c4f81334'
down_revision = '1e807f2c8231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['stockId'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stocks', sa.Column('ticker', sa.String(length=10), nullable=False))
    op.drop_column('stocks', 'name')
    op.drop_column('stocks', 'ticker')
    op.drop_column('stocks', 'exchange')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('exchange', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('stocks', sa.Column('ticker', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('stocks', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('stocks', 'ticker')
    op.drop_table('stocklists')
    # ### end Alembic commands ###
